name: Docker Image & Push in dockerhub CI 

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:
  
    name: Build-docker
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)


  Deploy:
    name: Push to dockerhub
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Push Docker Image
      uses: push-docker-image@v2.0.0
      with:
        image: sidtechanek/nodejs
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}